DROP TABLE backgrounds;
CREATE TABLE backgrounds (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  skill_proficiencies TEXT,
  tool_proficiencies TEXT,
  languages TEXT,
  equiptment TEXT
);

DROP TABLE background_features;
CREATE TABLE background_features (
  id INTEGER PRIMARY KEY,
  backgrounds_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  FOREIGN KEY (backgrounds_id) REFERENCES backgrounds(id)
);


-- PHB
INSERT INTO backgrounds VALUES (NULL, "Acolyte", "Insight, Religion", NULL, "Two of your choice", "A holy symbol (a gift to you when you entered the priesthood), a prayer book or prayer wheel, 5 sticks of incense, vestments, a set of common clothes, and a belt pouch containing 15 gp."); --
INSERT INTO background_features VALUES (NULL, 1, "Shelter of the Faithful", "As an acolyte, you command the respect of those who share your faith, and you can perform the religious ceremonies of your deity. You and your adventuring companions can expect to receive free healing and care at a temple, shrine, or other established presence of your faith, though you must provide any material components needed for spells. Those who share your religion will support you (but only you) at a modest lifestyle.<br><br>You might also have ties to a specific temple dedicated to your chosen deity or pantheon, and you have a residence there. This could be the temple where you used to serve, if you remain on good terms with it, or a temple where you have found a new home. While near your temple, you can call upon the priests for assistance, provided the assistance you ask for is not hazardous and you remain in good standing with your temple."); --

INSERT INTO backgrounds VALUES (NULL, "Charlatan", "Deception, Sleight of Hand", "Disguise kit, Forgery kit", NULL, "A set of fine clothes, a disguise kit, tools of the con of your choice (ten stoppered bottles filled with colored liquid, a set of weighted dice, a deck of marked cards, or a signet ring of an imaginary duke), and a belt pouch containing 15 gp."); --
INSERT INTO background_features VALUES (NULL, 2, "False Identity", "You have created a second identity that includes documentation, established acquaintances, and disguises that allow you to assume that persona. Additionally, you can forge documents including official papers and personal letters, as long as you have seen an example of the kind of document or the handwriting you are trying to copy."); --

INSERT INTO backgrounds VALUES (NULL, "Criminal", "Deception, Stealth", "One type of gaming set, thieves' tools", NULL, "A crowbar, a set of dark common clothes including a hood, and a belt pouch containing 15 gp."); --
INSERT INTO background_features VALUES (NULL, 3, "Criminal Contact", "You have a reliable and trustworthy contact who acts as your liaison to a network of other criminals. You know how to get messages to and from your contact, even over great distances; specifically, you know the local messengers, corrupt caravan masters, and seedy sailors who can deliver messages for you."); --

INSERT INTO backgrounds VALUES (NULL, "Criminal (Spy)", "Deception, Stealth", "One type of gaming set, thieves' tools", NULL, "A crowbar, a set of dark common clothes including a hood, and a belt pouch containing 15 gp."); --
INSERT INTO background_features VALUES (NULL, 4, "Spy Contact", "You have a reliable and trustworthy contact who acts as your liaison to a network of other spies. You know how to get messages to and from your contact, even over great distances; specifically, you know the local messengers, corrupt caravan masters, and seedy sailors who can deliver messages for you."); --

INSERT INTO backgrounds VALUES (NULL, "Entertainer", "Acrobatics, Performance", "Disguise kit, one type of musical instrument", NULL, "A musical instrument (one of your choice), the favor of an admirer (love letter, lock of hair, or trinket), costume clothes, and a belt pouch containing 15 gp."); --
INSERT INTO background_features VALUES (NULL, 5, "By Popular Demand", "You can always find a place to perform, usually in an inn or tavern but possibly with a circus, at a theater, or even in a noble's court. At such a place, you receive free lodging and food of a modest or comfortable standard (depending on the quality of the establishment), as long as you perform each night. In addition, your performance makes you something of a local figure. When strangers recognize you in a town where you have performed, they typically take a liking to you."); --

INSERT INTO backgrounds VALUES (NULL, "Entertainer (Gladiator)", "Acrobatics, Performance", "Disguise kit, one type of musical instrument", NULL, "An inexpensive but unusual weapon, such as a trident or net (one of your choice), the favor of an admirer (love letter, lock of hair, or trinket), costume clothes, and a belt pouch containing 15 gp"); --
INSERT INTO background_features VALUES (NULL, 6, "By Popular Demand", "You can always find a place to perform, usually in an inn or tavern but possibly with a circus, at a theater, or even in a noble's court. At such a place, you receive free lodging and food of a modest or comfortable standard (depending on the quality of the establishment), as long as you perform each night. In addition, your performance makes you something of a local figure. When strangers recognize you in a town where you have performed, they typically take a liking to you."); --

INSERT INTO backgrounds VALUES (NULL, "Folk Hero", "Animal Handling, Survival", "One type of artisan's tools, vehicles (land)", NULL, "A set of artisan's tools (one of your choice), a shovel, an iron pot, a set of common clothes, and a belt pouch containing 10 gp."); --
INSERT INTO background_features VALUES (NULL, 7, "Rustic Hospitality", "Since you come from the ranks of the common folk, you fit in among them with ease. You can find a place to hide, rest, or recuperate among other commoners, unless you have shown yourself to be a danger to them. They will shield you from the law or anyone else searching for you, though they will not risk their lives for you."); --

INSERT INTO backgrounds VALUES (NULL, "Guild Artisan", "Insight, Persuasion", "One type of artisan's tools", "One of your choice", "A set of artisan's tools (one of your choice), a letter of introduction from your guild, a set of traveler's clothes, and a belt pouch containing 15 gp."); --
INSERT INTO background_features VALUES (NULL, 8, "Guild Membership", "As an established and respected member of a guild, you can rely on certain benefits that membership provides. Your fellow guild members will provide you with lodging and food if necessary, and pay for your funeral if needed. In some cities and towns, a guildhall offers a central place to meet other members of your profession, which can be a good place to meet potential patrons, allies, or hirelings.<br><br>Guilds often wield tremendous political power. If you are accused of a crime, your guild will support you if a good case can be made for your innocence or the crime is justifiable. You can also gain access to powerful political figures through the guild, if you are a member in good standing. Such connections might require the donation of money or magic items to the guild's coffers.<br><br>You must pay dues of 5 gp per month to the guild. If you miss payments, you must make up back dues to remain in the guild's good graces."); --

INSERT INTO backgrounds VALUES (NULL, "Guild Artisan (Guild Merchant)", "Insight, Persuasion", "One type of artisan's tools, or navigator's tools, or an additional language", "One of your choice", "A set of artisan's tools (one of your choice) or a mule and cart, a letter of introduction from your guild, a set of traveler's clothes, and a belt pouch containing 15 gp"); --
INSERT INTO background_features VALUES (NULL, 9, "Guild Membership", "As an established and respected member of a guild, you can rely on certain benefits that membership provides. Your fellow guild members will provide you with lodging and food if necessary, and pay for your funeral if needed. In some cities and towns, a guildhall offers a central place to meet other members of your profession, which can be a good place to meet potential patrons, allies, or hirelings.<br><br>Guilds often wield tremendous political power. If you are accused of a crime, your guild will support you if a good case can be made for your innocence or the crime is justifiable. You can also gain access to powerful political figures through the guild, if you are a member in good standing. Such connections might require the donation of money or magic items to the guild's coffers.<br><br>You must pay dues of 5 gp per month to the guild. If you miss payments, you must make up back dues to remain in the guild's good graces."); --

INSERT INTO backgrounds VALUES (NULL, "Hermit", "Medicine, Religion", "Herbalism kit", "One of your choice", "A scroll case stuffed full of notes from your studies or prayers, a winter blanket, a set of common clothes, an herbalism kit, and 5 gp."); --
INSERT INTO background_features VALUES (NULL, 10, "Discovery", "The quiet seclusion of your extended hermitage gave you access to a unique and powerful discovery. The exact nature of this revelation depends on the nature of your seclusion. It might be a great truth about the cosmos, the deities, the powerful beings of the outer planes, or the forces of nature. It could be a site that no one else has ever seen. You might have uncovered a fact that has long been forgotten, or unearthed some relic of the past that could rewrite history. It might be information that would be damaging to the people who or consigned you to exile, and hence the reason for your return to society."); --

INSERT INTO backgrounds VALUES (NULL, "Noble", "History, Persuasion", "One type of gaming set", "One of your choice", "A set of fine clothes, a signet ring, a scroll of pedigree, and a purse containing 25 gp."); --
INSERT INTO background_features VALUES (NULL, 11, "Position of Privilege", "Thanks to your noble birth, people are inclined to think the best of you. You are welcome in high society, and people assume you have the right to be wherever you are. The common folk make every effort to accommodate you and avoid your displeasure, and other people of high birth treat you as a member of the same social sphere. You can secure an audience with a local noble if you need to."); --

INSERT INTO backgrounds VALUES (NULL, "Noble (Knight)", "History, Persuasion", "One type of gaming set", "One of your choice", "A set of fine clothes, a signet ring, a scroll of pedigree, and a purse containing 25 gp."); --
INSERT INTO background_features VALUES (NULL, 12, "Retainers", "You have the service of three retainers loyal to your family. These retainers can be attendants or messengers, and one might be a majordomo. One of your retainers is a noble who serves as your squire, aiding you in exchange for training on his or her own path to knighthood (This person could be your bond.). Your two remaining retainers might include a groom to care for your horse and a servant who polishes your armor (and even helps you put it on).<br><br>Your retainers can perform mundane tasks for you, but they do not fight for you, will not follow you into obviously dangerous areas (such as dungeons), and will leave if they are frequently endangered or abused."); --

INSERT INTO backgrounds VALUES (NULL, "Outlander", "Athletics, Survival", "One type of musical instrument", "One of your choice", "A staff, a hunting trap, a trophy from an animal you killed, a set of traveler's clothes, and a belt pouch containing 10 gp."); --
INSERT INTO background_features VALUES (NULL, 13, "Wanderer", "You have an excellent memory for maps and geography, and you can always recall the general layout of terrain, settlements, and other features around you. In addition, you can find food and fresh water for yourself and up to five other people each day, provided that the land offers berries, small game, water, and so forth."); --

INSERT INTO backgrounds VALUES (NULL, "Sage", "Arcana, History", NULL, "Two of your choice", "A bottle of black ink, a quill, a small knife, a letter from a dead colleague posing a question you have not yet been able to answer, a set of common clothes, and a belt pouch containing 10 gp."); --
INSERT INTO background_features VALUES (NULL, 14, "Researcher", "When you attempt to learn or recall a piece of lore, if you do not know that information, you often know where and from whom you can obtain it. Usually, this information comes from a library, scriptorium, university, or a sage or other learned person or creature. Your DM might rule that the knowledge you seek is secreted away in an almost inaccessible place, or that it simply cannot be found. Unearthing the deepest secrets of the multiverse can require an adventure or even a whole campaign."); --

INSERT INTO backgrounds VALUES (NULL, "Sailor", "Athletics, Perception", "Navigator's tools, vehicles (water)", NULL, "A belaying pin (club), silk rope (50 feet), a lucky charm such as a rabbit foot or a small stone with a hole in the center (or you may roll for a random trinket on the Trinkets table in chapter 5), a set of common clothes, and a belt pouch containing 10 gp."); --
INSERT INTO background_features VALUES (NULL, 15, "Ship's Passage", "When you need to, you can secure free passage on a sailing ship for yourself and your adventuring companions. You might sail on the ship you served on, or another ship you have good relations with (perhaps one captained by a former crewmate). Because you're calling in a favor, you can't be certain of a schedule or route that will meet your every need. Your Dungeon Master will determine how long it takes to get where you need to go. In return for your free passage, you and your companions are expected to assist the crew during the voyage."); --

INSERT INTO backgrounds VALUES (NULL, "Sailor (Pirate)", "Athletics, Perception", "Navigator's tools, vehicles (water)", NULL, "A belaying pin (club), silk rope (50 feet), a lucky charm such as a rabbit foot or a small stone with a hole in the center (or you may roll for a random trinket on the Trinkets table in chapter 5), a set of common clothes, and a belt pouch containing 10 gp."); --
INSERT INTO background_features VALUES (NULL, 16, "Bad Reputation", "No matter where you go, people are afraid of you due to your reputation. When you are in a civilized settlement, you can get away with minor criminal offenses, such as refusing to pay for food at a tavern or breaking down doors at a local shop, since most people will not report your activity to the authorities."); --

INSERT INTO backgrounds VALUES (NULL, "Soldier", "Athletics, Intimidation", "One type of gaming set, vehicles (land)", NULL, "An insignia of rank, a trophy taken from a fallen enemy (a dagger, broken blade, or piece of a banner), a bone dice set or playing card set, a set of common clothes, and a belt pouch containing 10 gp."); --
INSERT INTO background_features VALUES (NULL, 17, "Military Rank", "You have a military rank from your career as a soldier. Soldiers loyal to your former military organization still recognize your authority and influence, and they defer to you if they are of a lower rank. You can invoke your rank to exert influence over other soldiers and requisition simple equipment or horses for temporary use. You can also usually gain access to friendly military encampments and fortresses where your rank is recognized."); --

INSERT INTO backgrounds VALUES (NULL, "Urchin", "Sleight of Hand, Stealth", "Disguise kit, Thieves' tools", NULL, "A small knife, a map of the city you grew up in, a pet mouse, a token to remember your parents by, a set of common clothes, and a belt pouch containing 10 gp."); --
INSERT INTO background_features VALUES (NULL, 18, "City Secrets", "You know the secret patterns and flow to cities and can find passages through the urban sprawl that others would miss. When you are not in combat, you (and companions you lead) can travel between any two locations in the city twice as fast as your speed would normally allow."); --


-- AI
INSERT INTO backgrounds VALUES (NULL, "Celebrity Adventurer's Scion", "Perception, Performance", "Disguise kit", "Two of your choice", "Disguise kit, a set of fine clothes, and a belt pouch containing 30 gp."); --
INSERT INTO background_features VALUES (NULL, 19, "Name Dropping", "You know and have met any number of powerful people across the land—and some of them might even remember you. You might be able to wrangle minor assistance from a major figure in the campaign, at the DM's discretion. Additionally, the common folk treat you with deference, and your heritage and the stories you tell might be good for a free meal or a place to sleep."); --

INSERT INTO backgrounds VALUES (NULL, "Failed Merchant", "Investigation, Persuasion", "One type of artisan's tools", "Any one of your choice", "One set of artisan's tools, merchant's scale, a set of fine clothes, and a belt pouch containing 10 gp"); --
INSERT INTO background_features VALUES (NULL, 20, "Supply Chain", "From your time as a merchant, you retain connections with wholesalers, suppliers, and other merchants and entrepreneurs. You can call upon these connections when looking for items or information."); --

INSERT INTO backgrounds VALUES (NULL, "Gambler", "Deception, Insight", "One gaming set", "Any one of your choice", "One gaming set, a lucky charm, a set of fine clothes, and a belt pouch containing 15 gp."); --
INSERT INTO background_features VALUES (NULL, 21, "Never Tell Me the Odds", "Odds and probability are your bread and butter. During downtime activities that involve games of chance or figuring odds on the best plan, you can get a solid sense of which choice is likely the best one and which opportunities seem too good to be true, at the DM's determination."); --

INSERT INTO backgrounds VALUES (NULL, "Plaintiff", "Medicine, Persuasion", "One type of artisan's tools", "Any one of your choice", "One set of artisan's tools, fine clothes, 20 gp."); --
INSERT INTO background_features VALUES (NULL, 22, "Legalese", "Your experience with your local legal system has given you a firm knowledge of the ins and outs of that system. Even when the law is not on your side, you can use complex terms like ex injuria jus non oritur and cogitationis poenam nemo patitur to frighten people into thinking you know what you're talking about. With common folks who don't know any better, you might be able to intimidate or deceive to get favors or special treatment."); --

INSERT INTO backgrounds VALUES (NULL, "Rival Intern", "History, Investigation", "One type of artisan's tools", "Any one of your choice", "One set of artisan's tools, a ledger from your previous employer containing a small piece of useful information, a set of fine clothes, and a belt pouch containing 10 gp."); --
INSERT INTO background_features VALUES (NULL, 23, "Inside Informant", "You have connections to your previous employer or other groups you dealt with during your previous employment. You can communicate with your contacts, gaining information at the DM's discretion."); --


-- BG:DiA
INSERT INTO backgrounds VALUES (NULL, "Faceless", "Deception, Intimidation", "Disguise kit", "One of your choice", "Disguise kit, a costume, a pouch containing 10 gp"); --
INSERT INTO background_features VALUES (NULL, 24, "Dual Personalities", "Most of your fellow adventurers and the world know you as your persona. Those who seek to learn more about you—your weaknesses, your origins, your purpose—find themselves stymied by your disguise. Upon donning a disguise and behaving as your persona, you are unidentifiable as your true self. By removing your disguise and revealing your true face, you are no longer identifiable as your persona. This allows you to change appearances between your two personalities as often as you wish, using one to hide the other or serve as convenient camouflage. However, should someone realize the connection between your persona and your true self, your deception might lose its effectiveness."); --


-- COS
INSERT INTO backgrounds VALUES (NULL, "Haunted One", "Choose two from among Arcana, Investigation, Religion, or Survival", NULL, "Choose two, one of which must be Abyssal, Celestial, Deep Speech, Draconic, Infernal, Primordial, Sylvan, or Undercommon", "Monster hunter's pack (containing a chest, a crowbar, a hammer, three wooden stakes, a holy symbol, a flask of holy water, a set of manacles, a steel mirror, a flask of oil, a tinderbox, and 3 torches), a set of common clothes, one trinket of special significance (choose one or roll on the Horror Trinkets table), and 1 sp."); --
INSERT INTO background_features VALUES (NULL, 25, "Heart of Darkness", "Those who look into your eyes can see that you have faced unimaginable horror and that you are no stranger to darkness. Though they might fear you, commoners will extend you every courtesy and do their utmost to help you. Unless you have shown yourself to be a danger to them, they will even take up arms to fight alongside you, should you find yourself facing an enemy alone."); --


-- E:RftLW
INSERT INTO backgrounds VALUES (NULL, "House Agent", "Investigation, Persuasion", "Two proficiencies from the House Tool Proficiencies table", NULL, "A set of fine clothes, house signet ring, identification papers, and a purse containing 20 gp."); --
INSERT INTO background_features VALUES (NULL, 26, "House Connections", "As an agent of your house, you can always get food and lodging for yourself and your friends at a house enclave. When the house assigns you a mission, it will usually provide you with the necessary supplies and transportation. Beyond this, you have many old friends, mentors, and rivals in your house, and you may encounter one of them when you interact with a house business. The degree to which such acquaintances are willing to help you depends on your current standing in your house."); --


-- GOS
INSERT INTO backgrounds VALUES (NULL, "Fisher", "History, Survival", NULL, "One of your choice", "Fishing tackle, a net, a favorite fishing lure or oiled leather wading boots, a set of traveler's clothes, and a belt pouch containing 10 gp."); --
INSERT INTO background_features VALUES (NULL, 27, "Harvest the Water", "You gain advantage on ability checks made using fishing tackle. If you have access to a body of water that sustains marine life, you can maintain a moderate lifestyle while working as a fisher, and you can catch enough food to feed yourself and up to ten other people each day."); --

INSERT INTO backgrounds VALUES (NULL, "Marine", "Athletics, Survival", "Vehicles (water, land)", NULL, "A dagger that belonged to a fallen comrade, a folded flag emblazoned with the symbol of your ship or company, a set of traveler's clothes, and a belt pouch containing 10 gp."); --
INSERT INTO background_features VALUES (NULL, 28, "Steady", "You can move twice the normal amount of time (up to 16 hours) each day before being subject to the effect of a forced march (see 'Travel Pace' in chapter 8 of the Player's Handbook). Additionally, you can automatically find a safe route to land a boat on shore, provided such a route exists."); --

INSERT INTO backgrounds VALUES (NULL, "Shipwright", "History, Perception", "Carpenter's tools, Vehicles (water)", NULL, "A set of well-loved carpenter's tools, a blank book, 1 ounce of ink, an ink pen, a set of traveler's clothes, and a leather pouch with 10 gp."); --
INSERT INTO background_features VALUES (NULL, 29, "I'll Patch It!", "Provided you have carpenter's tools and wood, you can perform repairs on a water vehicle. When you use this ability, you restore a number of hit points to the hull of a water vehicle equal to 5 × your proficiency modifier. A vehicle cannot be patched by you in this way again until after it has been pulled ashore and fully repaired."); --

INSERT INTO backgrounds VALUES (NULL, "Smuggler", "Athletics, Deception", "Vehicles (water)", NULL, "A fancy leather vest or a pair of leather boots, a set of common clothes, and a leather pouch with 15 gp."); --
INSERT INTO background_features VALUES (NULL, 30, "Down Low", "You are acquainted with a network of smugglers who are willing to help you out of tight situations. While in a particular town, city, or other similarly sized community (DM's discretion), you and your companions can stay for free in safe houses. Safe houses provide a poor lifestyle. While staying at a safe house, you can choose to keep your presence (and that of your companions) a secret."); --


-- MOoT
INSERT INTO backgrounds VALUES (NULL, "Athlete", "Acrobatics, Athletics", "Vehicles (land)", "One of your choice", "A bronze discus or leather ball, a lucky charm or past trophy, a set of traveler's clothes, and a pouch containing 10 gp."); --
INSERT INTO background_features VALUES (NULL, 31, "Echoes of Victory", "You have attracted admiration among spectators, fellow athletes, and trainers in the region that hosted your past athletic victories. When visiting any settlement within 100 miles of where you grew up, there is a 50 percent chance you can find someone there who admires you and is willing to provide information or temporary shelter.<br><br>Between adventures, you might compete in athletic events sufficient enough to maintain a comfortable lifestyle, as per the 'Practicing a Profession' downtime activity in chapter 8 of the Player's Handbook."); --


-- SCAG
INSERT INTO backgrounds VALUES (NULL, "City Watch", "Athletics, Insight", NULL, "Any two of your choice", "A uniform in the style of your unit and indicative of your rank, a horn with which to summon help, a set of manacles, and a pouch containing 10 gp."); --
INSERT INTO background_features VALUES (NULL, 32, "Watcher's Eye", "Your experience in enforcing the law, and dealing with lawbreakers, gives you a feel for local laws and criminals. You can easily find the local outpost of the watch or a similar organization, and just as easily pick out the dens of criminal activity in a community, although you're more likely to be welcome in the former locations rather than the latter."); --

INSERT INTO backgrounds VALUES (NULL, "City Watch (Investigator)", "Insight, Investigation", NULL, "Any two of your choice", "A uniform in the style of your unit and indicative of your rank, a horn with which to summon help, a set of manacles, and a pouch containing 10 gp."); --
INSERT INTO background_features VALUES (NULL, 33, "Watcher's Eye", "Your experience in enforcing the law, and dealing with lawbreakers, gives you a feel for local laws and criminals. You can easily find the local outpost of the watch or a similar organization, and just as easily pick out the dens of criminal activity in a community, although you're more likely to be welcome in the former locations rather than the latter."); --

INSERT INTO backgrounds VALUES (NULL, "Clan Crafter", "History, Insight", "One type of artisan's tools", "Dwarvish or one of your choice if you already speak Dwarvish", "A set of artisan's tools with which you are proficient, a maker's mark chisel used to mark your handiwork with the symbol of the clan of crafters you learned your skill from, a set of traveler's clothes, and a pouch containing 5 gp and a gem worth 10 gp."); --
INSERT INTO background_features VALUES (NULL, 34, "Respect of the Stout Folk", "As well respected as clan crafters are among outsiders, no one esteems them quite so highly as dwarves do. You always have free room and board in any place where shield dwarves or gold dwarves dwell, and the individuals in such a settlement might vie among themselves to determine who can offer you (and possibly your companions) the finest accommodations and assistance."); --

INSERT INTO backgrounds VALUES (NULL, "Cloistered Scholar", "History, plus your choice of one from among Arcana, Nature, and Religion", NULL, "Any two of your choice", "The scholar's robes of your cloister, a writing kit (small pouch with a quill, ink, folded parchment, and a small penknife), a borrowed book on the subject of your current study, and a pouch containing 10 gp."); --
INSERT INTO background_features VALUES (NULL, 35, "Library Access", "Though others must often endure extensive interviews and significant fees to gain access to even the most common archives in your library, you have free and easy access to the majority of the library, though it might also have repositories of lore that are too valuable, magical, or secret to permit anyone immediate access.<br><br>You have a working knowledge of your cloister's personnel and bureaucracy, and you know how to navigate those connections with some ease.<br><br>Additionally, you are likely to gain preferential treatment at other libraries across the Realms, as professional courtesy to a fellow scholar."); --

INSERT INTO backgrounds VALUES (NULL, "Courtier", "Insight, Persuasion", NULL, "Any two of your choice", "A set of fine clothes and a pouch containing 5 gp"); --
INSERT INTO background_features VALUES (NULL, 36, "Court Functionary", "Your knowledge of how bureaucracies function lets you gain access to the records and inner workings of any noble court or government you encounter. You know who the movers and shakers are, whom to go to for the favors you seek, and what the current intrigues of interest in the group are."); --

INSERT INTO backgrounds VALUES (NULL, "Faction Agent", "Insight and one Intelligence, Wisdom, or Charisma skill of your choice, as appropriate to your faction", NULL, "Any two of your choice", "Badge or emblem of your faction, a copy of a seminal faction text (or code-book for a covert faction), a set of common clothes, and a pouch containing 15 gp."); --
INSERT INTO background_features VALUES (NULL, 37, "Safe Haven", "As a faction agent, you have access to a secret network of supporters and operatives who can provide assistance on your adventures. You know a set of secret signs and passwords you can use to identify such operatives, who can provide you with access to a hidden safe house, free room and board, or assistance in finding information. These agents never risk their lives for you or risk revealing their true identities."); --

INSERT INTO backgrounds VALUES (NULL, "Far Traveler", "Insight, Perception", "Any one musical instrument or gaming set of your choice, likely something native to your homeland", "Any one of your choice", "One set of traveler's clothes, any one musical instrument or gaming set you are proficient with, poorly wrought maps from your homeland that depict where you are in Faerûn, a small piece of jewelry worth 10 gp in the style of your homeland's craftsmanship, and a pouch containing 5 gp."); --
INSERT INTO background_features VALUES (NULL, 38, "All Eyes on You", "Your accent, mannerisms, figures of speech, and perhaps even your appearance all mark you as foreign. Curious glances are directed your way wherever you go, which can be a nuisance, but you also gain the friendly interest of scholars and others intrigued by far-off lands, to say nothing of everyday folk who are eager to hear stories of your homeland.<br><br>You can parley this attention into access to people and places you might not otherwise have, for you and your traveling companions. Noble lords, scholars, and merchant princes, to name a few, might be interested in hearing about your distant homeland and people."); --

INSERT INTO backgrounds VALUES (NULL, "Inheritor", "Survival, plus one from among Arcana, History, and Religion", "Your choice of a gaming set or a musical instrument", "Any one of your choice", "Your inheritance, a set of traveler's clothes, the tool you choose for this background's tool proficiency (gaming set or musical instrument), and a pouch containing 15 gp."); --
INSERT INTO background_features VALUES (NULL, 39, "Inheritance", "Choose or randomly determine your inheritance from the possibilities in the table below. Work with your Dungeon Master to come up with details: Why is your inheritance so important, and what is its full story? You might prefer for the DM to invent these details as part of the game, allowing you to learn more about your inheritance as your character does.<br><br>The Dungeon Master is free to use your inheritance as a story hook, sending you on quests to learn more about its history or true nature, or confronting you with foes who want to claim it for themselves or prevent you from learning what you seek. The DM also determines the properties of your inheritance and how they figure into the item's history and importance. For instance, the object might be a minor magic item, or one that begins with a modest ability and increases in potency with the passage of time. Or, the true nature of your inheritance might not be apparent at first and is revealed only when certain conditions are met.<br><br>When you begin your adventuring career, you can decide whether to tell your companions about your inheritance right away. Rather than attracting attention to yourself, you might want to keep your inheritance a secret until you learn more about what it means to you and what it can do for you."); --

INSERT INTO backgrounds VALUES (NULL, "Knight of the Order", "Persuasion, plus one from among Arcana, History, Nature, and Religion, as appropriate for your order", "Your choice of a gaming set or a musical instrument", "Any one of your choice", "One set of traveler's clothes, a signet, banner, or seal representing your place or rank in the order, and a pouch containing 10 gp."); --
INSERT INTO background_features VALUES (NULL, 40, "Knightly Regard", "You receive shelter and succor from members of your knightly order and those who are sympathetic to its aims. If your order is a religious one, you can gain aid from temples and other religious communities of your deity. Knights of civic orders can get help from the community—whether a lone settlement or a great nation—that they serve, and knights of philosophical orders can find help from those they have aided in pursuit of their ideals, and those who share their ideals.<br><br>This help comes in the form of shelter and meals, and healing when appropriate, as well as occasionally risky assistance, such as a band of local citizens rallying to aid a sorely pressed knight, or those who support the order helping to smuggle a knight out of town when he or she is being hunted unjustly."); --

INSERT INTO backgrounds VALUES (NULL, "Mercenary Veteran", "Athletics, Persuasion", "One type of gaming set, vehicles (land)", NULL, "A uniform of your company (traveler's clothes in quality), an insignia of your rank, a gaming set of your choice, and a pouch containing the remainder of your last wages (10 gp)."); --
INSERT INTO background_features VALUES (NULL, 41, "Mercenary Life", "You know the mercenary life as only someone who has experienced it can. You are able to identify mercenary companies by their emblems, and you know a little about any such company, including who has hired them recently. You can find the taverns and festhalls where mercenaries abide in any area, as long as you speak the language. You can find mercenary work between adventures sufficient to maintain a comfortable lifestyle (see 'Practicing a Profession' under 'Downtime Activities' in chapter 8 of the Player's Handbook)."); --

INSERT INTO backgrounds VALUES (NULL, "Urban Bounty Hunter", "Choose two from among Deception, Insight, Persuasion, and Stealth", "Choose two from among one type of gaming set, one musical instrument, and thieves' tools", NULL, "A set of clothes appropriate to your duties and a pouch containing 20 gp."); --
INSERT INTO background_features VALUES (NULL, 42, "Ear to the Ground", "You are in frequent contact with people in the segment of society that your chosen quarries move through. These people might be associated with the criminal underworld, the rough-and-tumble folk of the streets, or members of high society. This connection comes in the form of a contact in any city you visit, a person who provides information about the people and places of the local area."); --

INSERT INTO backgrounds VALUES (NULL, "Tribe Member", "Athletics, Survival", "One type of musical instrument or artisan's tools", "Any one of your choice", "A hunting trap, a totemic token or set of tattoos marking your loyalty to Uthgar and your tribal totem, a set of traveler's clothes, and a pouch containing 10 gp"); --
INSERT INTO background_features VALUES (NULL, 43, "Tribal Heritage", "You have an excellent knowledge of not only your tribe's territory, but also the terrain and natural resources of the rest of the North. You are familiar enough with any wilderness area that you can find twice as much food and water as you normally would when you forage there.<br><br>Additionally, you can call upon the hospitality of your people, and those allied with your tribe, often including members of the druid circles, tribes of nomadic elves, the Harpers, and the priesthoods devoted to the gods of the First Circle."); --


-- ToA
INSERT INTO backgrounds VALUES (NULL, "Anthropologist", "Insight, Religion", NULL, "Two of your choice", "A leather-bound diary, a bottle of ink, an ink pen, a set of traveler's clothes, one trinket of special significance, and a pouch containing 10 gp"); --
INSERT INTO background_features VALUES (NULL, 44, "Adept Linguist", "You can communicate with humanoids who don't speak any language you know. You must observe the humanoids interacting with one another for at least 1 day, after which you learn a handful of important words, expressions, and gestures - enough to communicate on a rudimentary level."); --

INSERT INTO backgrounds VALUES (NULL, "Archaeologist", "History, Survival", "Cartographer's tools or navigator's tools", "One of your choice", "A wooden case containing a map to a ruin or dungeon, a bullseye lantern, a miner's pick, a set of traveler's clothes, a shovel, a two-person tent, a trinket recovered from a dig site, and a pouch containing 25 gp."); --
INSERT INTO background_features VALUES (NULL, 45, "Historical Knowledge", "When you enter a ruin or dungeon, you can correctly ascertain its original purpose and determine its builders, whether those were dwarves, elves, humans, yuan-ti, or some other known race. In addition, you can determine the monetary value of art objects more than a century old."); --


-- VRG
INSERT INTO backgrounds VALUES (NULL, "Investigator", "Choose two from among Insight, Investigation, or Perception", "Disguise kit, Thieves' tools", NULL, "A magnifying glass, evidence from a past case (choose one or roll for a trinket from the Horror Trinkets later in this chapter), a set of common clothes, and 10 gp."); --
INSERT INTO background_features VALUES (NULL, 46, "Official Inquiry", "You're experienced at gaining access to people and places to get the information you need. Through a combination of fast-talking, determination, and official-looking documentation, you can gain access to a place or an individual related to a crime you're investigating. Those who aren't involved in your investigation avoid impeding you or pass along your requests. Additionally, local law enforcement has firm opinions about you, viewing you as either a nuisance or one of their own."); --

