DROP TABLE BARDSPELLS;
CREATE TABLE BARDSPELLS(
	ID INTEGER PRIMARY KEY NOT NULL,
	NAME TEXT NOT NULL
);

DROP TABLE CLERICSPELLS;
CREATE TABLE CLERICSPELLS(
	ID INTEGER PRIMARY KEY NOT NULL,
	NAME TEXT NOT NULL
);

DROP TABLE DRUIDSPELLS;
CREATE TABLE DRUIDSPELLS(
	ID INTEGER PRIMARY KEY NOT NULL,
	NAME TEXT NOT NULL
);

DROP TABLE PALADINSPELLS;
CREATE TABLE PALADINSPELLS(
	ID INTEGER PRIMARY KEY NOT NULL,
	NAME TEXT NOT NULL
);

DROP TABLE RANGERSPELLS;
CREATE TABLE RANGERSPELLS(
	ID INTEGER PRIMARY KEY NOT NULL,
	NAME TEXT NOT NULL
);

DROP TABLE SORCERERSPELLS;
CREATE TABLE SORCERERSPELLS(
	ID INTEGER PRIMARY KEY NOT NULL,
	NAME TEXT NOT NULL
);

DROP TABLE WARLOCKSPELLS;
CREATE TABLE WARLOCKSPELLS(
	ID INTEGER PRIMARY KEY NOT NULL,
	NAME TEXT NOT NULL
);

DROP TABLE WIZARDSPELLS;
CREATE TABLE WIZARDSPELLS(
	ID INTEGER PRIMARY KEY NOT NULL,
	NAME TEXT NOT NULL
);

-- BARDSPELLS SPELLS
-- PHB
INSERT INTO BARDSPELLS VALUES (NULL, "Blade Ward");							-- 0
INSERT INTO BARDSPELLS VALUES (NULL, "Dancing Lights");
INSERT INTO BARDSPELLS VALUES (NULL, "Friends");
INSERT INTO BARDSPELLS VALUES (NULL, "Light");
INSERT INTO BARDSPELLS VALUES (NULL, "Mage Hand");
INSERT INTO BARDSPELLS VALUES (NULL, "Mending");
INSERT INTO BARDSPELLS VALUES (NULL, "Message");
INSERT INTO BARDSPELLS VALUES (NULL, "Minor Illusion");
INSERT INTO BARDSPELLS VALUES (NULL, "Prestidigitation");
INSERT INTO BARDSPELLS VALUES (NULL, "True Strike");
INSERT INTO BARDSPELLS VALUES (NULL, "Vicious Mockery");
INSERT INTO BARDSPELLS VALUES (NULL, "Animal Friendship");			-- 1
INSERT INTO BARDSPELLS VALUES (NULL, "Bane");
INSERT INTO BARDSPELLS VALUES (NULL, "Charm Person");
INSERT INTO BARDSPELLS VALUES (NULL, "Comprehend Languages");
INSERT INTO BARDSPELLS VALUES (NULL, "Cure Wounds");
INSERT INTO BARDSPELLS VALUES (NULL, "Detect Magic");
INSERT INTO BARDSPELLS VALUES (NULL, "Disguise Self");
INSERT INTO BARDSPELLS VALUES (NULL, "Dissonant Whispers");
INSERT INTO BARDSPELLS VALUES (NULL, "Faerie Fire");
INSERT INTO BARDSPELLS VALUES (NULL, "Feather Fall");
INSERT INTO BARDSPELLS VALUES (NULL, "Healing Word");
INSERT INTO BARDSPELLS VALUES (NULL, "Heroism");
INSERT INTO BARDSPELLS VALUES (NULL, "Identify");
INSERT INTO BARDSPELLS VALUES (NULL, "Illusory Script");
INSERT INTO BARDSPELLS VALUES (NULL, "Longstrider");
INSERT INTO BARDSPELLS VALUES (NULL, "Silent Image");
INSERT INTO BARDSPELLS VALUES (NULL, "Sleep");
INSERT INTO BARDSPELLS VALUES (NULL, "Speak With Animals");
INSERT INTO BARDSPELLS VALUES (NULL, "Tasha's Hideous Laughter");
INSERT INTO BARDSPELLS VALUES (NULL, "Thunderwave");
INSERT INTO BARDSPELLS VALUES (NULL, "Unseen Servant");
INSERT INTO BARDSPELLS VALUES (NULL, "Animal Messenger");				-- 2
INSERT INTO BARDSPELLS VALUES (NULL, "Blindness/Deafness");
INSERT INTO BARDSPELLS VALUES (NULL, "Calm Emotions");
INSERT INTO BARDSPELLS VALUES (NULL, "Cloud of Daggers");
INSERT INTO BARDSPELLS VALUES (NULL, "Crown of Madness");
INSERT INTO BARDSPELLS VALUES (NULL, "Detect Thoughts");
INSERT INTO BARDSPELLS VALUES (NULL, "Enhance Ability");
INSERT INTO BARDSPELLS VALUES (NULL, "Enthrall");
INSERT INTO BARDSPELLS VALUES (NULL, "Heat Metal");
INSERT INTO BARDSPELLS VALUES (NULL, "Hold Person");
INSERT INTO BARDSPELLS VALUES (NULL, "Invisibility");
INSERT INTO BARDSPELLS VALUES (NULL, "Knock");
INSERT INTO BARDSPELLS VALUES (NULL, "Lesser Restoration");
INSERT INTO BARDSPELLS VALUES (NULL, "Locate Animals or Plants");
INSERT INTO BARDSPELLS VALUES (NULL, "Locate Object");
INSERT INTO BARDSPELLS VALUES (NULL, "Magic Mouth");
INSERT INTO BARDSPELLS VALUES (NULL, "Phantasmal Force");
INSERT INTO BARDSPELLS VALUES (NULL, "See Invisibility");
INSERT INTO BARDSPELLS VALUES (NULL, "Shatter");
INSERT INTO BARDSPELLS VALUES (NULL, "Silence");
INSERT INTO BARDSPELLS VALUES (NULL, "Suggestion");
INSERT INTO BARDSPELLS VALUES (NULL, "Zone of Truth");
INSERT INTO BARDSPELLS VALUES (NULL, "Bestow Curse");						-- 3
INSERT INTO BARDSPELLS VALUES (NULL, "Clairvoyance");
INSERT INTO BARDSPELLS VALUES (NULL, "Dispel Magic");
INSERT INTO BARDSPELLS VALUES (NULL, "Fear");
INSERT INTO BARDSPELLS VALUES (NULL, "Feign Death");
INSERT INTO BARDSPELLS VALUES (NULL, "Glyph of Warding");
INSERT INTO BARDSPELLS VALUES (NULL, "Hypnotic Pattern");
INSERT INTO BARDSPELLS VALUES (NULL, "Leomund's Tiny Hut");
INSERT INTO BARDSPELLS VALUES (NULL, "Major Image");
INSERT INTO BARDSPELLS VALUES (NULL, "Nondetection");
INSERT INTO BARDSPELLS VALUES (NULL, "Plant Growth");
INSERT INTO BARDSPELLS VALUES (NULL, "Sending");
INSERT INTO BARDSPELLS VALUES (NULL, "Speak with Dead");
INSERT INTO BARDSPELLS VALUES (NULL, "Speak with Plants");
INSERT INTO BARDSPELLS VALUES (NULL, "Stinking Cloud");
INSERT INTO BARDSPELLS VALUES (NULL, "Tongues");
INSERT INTO BARDSPELLS VALUES (NULL, "Compulsion");							-- 4
INSERT INTO BARDSPELLS VALUES (NULL, "Confusion");
INSERT INTO BARDSPELLS VALUES (NULL, "Dimension Door");
INSERT INTO BARDSPELLS VALUES (NULL, "Freedom of Movement");
INSERT INTO BARDSPELLS VALUES (NULL, "Greater Invisibility");
INSERT INTO BARDSPELLS VALUES (NULL, "Hallucinatory Terrain");
INSERT INTO BARDSPELLS VALUES (NULL, "Locate Creature");
INSERT INTO BARDSPELLS VALUES (NULL, "Polymorph");
INSERT INTO BARDSPELLS VALUES (NULL, "Animate Objects");				-- 5
INSERT INTO BARDSPELLS VALUES (NULL, "Awaken");
INSERT INTO BARDSPELLS VALUES (NULL, "Dominate Person");
INSERT INTO BARDSPELLS VALUES (NULL, "Dream");
INSERT INTO BARDSPELLS VALUES (NULL, "Geas");
INSERT INTO BARDSPELLS VALUES (NULL, "Greater Restoration");
INSERT INTO BARDSPELLS VALUES (NULL, "Hold Monster");
INSERT INTO BARDSPELLS VALUES (NULL, "Legend Lore");
INSERT INTO BARDSPELLS VALUES (NULL, "Mass Cure Wounds");
INSERT INTO BARDSPELLS VALUES (NULL, "Mislead");
INSERT INTO BARDSPELLS VALUES (NULL, "Modify Memory");
INSERT INTO BARDSPELLS VALUES (NULL, "Planar Binding");
INSERT INTO BARDSPELLS VALUES (NULL, "Raise Dead");
INSERT INTO BARDSPELLS VALUES (NULL, "Scrying");
INSERT INTO BARDSPELLS VALUES (NULL, "Seeming");
INSERT INTO BARDSPELLS VALUES (NULL, "Teleportation Circle");
INSERT INTO BARDSPELLS VALUES (NULL, "Eyebite");								-- 6
INSERT INTO BARDSPELLS VALUES (NULL, "Find the Path");
INSERT INTO BARDSPELLS VALUES (NULL, "Guards and Wards");
INSERT INTO BARDSPELLS VALUES (NULL, "Mass Suggestion");
INSERT INTO BARDSPELLS VALUES (NULL, "Otto's Irresistible Dance");
INSERT INTO BARDSPELLS VALUES (NULL, "Programmed Illusion");
INSERT INTO BARDSPELLS VALUES (NULL, "True Seeing");
INSERT INTO BARDSPELLS VALUES (NULL, "Etherealness");						-- 7
INSERT INTO BARDSPELLS VALUES (NULL, "Forcecage");
INSERT INTO BARDSPELLS VALUES (NULL, "Mirage Arcane");
INSERT INTO BARDSPELLS VALUES (NULL, "Mordenkainen's Magnificent Mansion");
INSERT INTO BARDSPELLS VALUES (NULL, "Mordenkainen's Sword");
INSERT INTO BARDSPELLS VALUES (NULL, "Project Image");
INSERT INTO BARDSPELLS VALUES (NULL, "Regenerate");
INSERT INTO BARDSPELLS VALUES (NULL, "Resurrection");
INSERT INTO BARDSPELLS VALUES (NULL, "Symbol");
INSERT INTO BARDSPELLS VALUES (NULL, "Teleport");
INSERT INTO BARDSPELLS VALUES (NULL, "Dominate Monster");					-- 8
INSERT INTO BARDSPELLS VALUES (NULL, "Feeblemind");
INSERT INTO BARDSPELLS VALUES (NULL, "Glibness");
INSERT INTO BARDSPELLS VALUES (NULL, "Mind Blank");
INSERT INTO BARDSPELLS VALUES (NULL, "Power Word Stun");
INSERT INTO BARDSPELLS VALUES (NULL, "Foresight");								-- 9
INSERT INTO BARDSPELLS VALUES (NULL, "Power Word Heal");
INSERT INTO BARDSPELLS VALUES (NULL, "Power Word Kill");
INSERT INTO BARDSPELLS VALUES (NULL, "True Polymorph");
-- XGE
INSERT INTO BARDSPELLS VALUES (NULL, "Thunderclap");
INSERT INTO BARDSPELLS VALUES (NULL, "Earth Tremor");
INSERT INTO BARDSPELLS VALUES (NULL, "Pyrotechnics");
INSERT INTO BARDSPELLS VALUES (NULL, "Skywrite");
INSERT INTO BARDSPELLS VALUES (NULL, "Warding Wind");
INSERT INTO BARDSPELLS VALUES (NULL, "Catnap");
INSERT INTO BARDSPELLS VALUES (NULL, "Enemies Abound");
INSERT INTO BARDSPELLS VALUES (NULL, "Charm Monster");
INSERT INTO BARDSPELLS VALUES (NULL, "Skill Empowerment");
INSERT INTO BARDSPELLS VALUES (NULL, "Synaptic Static");
INSERT INTO BARDSPELLS VALUES (NULL, "Mass Polymorph");
INSERT INTO BARDSPELLS VALUES (NULL, "Psychic scream");
-- TCE
INSERT INTO BARDSPELLS VALUES (NULL, "Intellect Fortress");
INSERT INTO BARDSPELLS VALUES (NULL, "Dream of the Blue Veil");

-- CLERICSPELLS SPELLS
-- PHB
INSERT INTO CLERICSPELLS VALUES (NULL, "Guidance");										-- 0
INSERT INTO CLERICSPELLS VALUES (NULL, "Light");
INSERT INTO CLERICSPELLS VALUES (NULL, "Mending");
INSERT INTO CLERICSPELLS VALUES (NULL, "Resistance");
INSERT INTO CLERICSPELLS VALUES (NULL, "Sacred Flame");
INSERT INTO CLERICSPELLS VALUES (NULL, "Spare the Dying");
INSERT INTO CLERICSPELLS VALUES (NULL, "Thaumaturgy");
INSERT INTO CLERICSPELLS VALUES (NULL, "Bane");												-- 1
INSERT INTO CLERICSPELLS VALUES (NULL, "Bless");
INSERT INTO CLERICSPELLS VALUES (NULL, "Command");
INSERT INTO CLERICSPELLS VALUES (NULL, "Create or Destroy Water");
INSERT INTO CLERICSPELLS VALUES (NULL, "Cure Wounds");
INSERT INTO CLERICSPELLS VALUES (NULL, "Detect Evil and Good");
INSERT INTO CLERICSPELLS VALUES (NULL, "Detect Magic");
INSERT INTO CLERICSPELLS VALUES (NULL, "Detect Poison and Disease");
INSERT INTO CLERICSPELLS VALUES (NULL, "Guiding Bolt");
INSERT INTO CLERICSPELLS VALUES (NULL, "Healing Word");
INSERT INTO CLERICSPELLS VALUES (NULL, "Inflict Wounds");
INSERT INTO CLERICSPELLS VALUES (NULL, "Protection from Evil and Good");
INSERT INTO CLERICSPELLS VALUES (NULL, "Purify Food and Drink");
INSERT INTO CLERICSPELLS VALUES (NULL, "Sanctuary");
INSERT INTO CLERICSPELLS VALUES (NULL, "Shield of Faith");
INSERT INTO CLERICSPELLS VALUES (NULL, "Aid");												-- 2
INSERT INTO CLERICSPELLS VALUES (NULL, "Augury");
INSERT INTO CLERICSPELLS VALUES (NULL, "Blindness/Deafness");
INSERT INTO CLERICSPELLS VALUES (NULL, "Calm Emotions");
INSERT INTO CLERICSPELLS VALUES (NULL, "Continual Flame");
INSERT INTO CLERICSPELLS VALUES (NULL, "Enhance Abilities");
INSERT INTO CLERICSPELLS VALUES (NULL, "Find Traps");
INSERT INTO CLERICSPELLS VALUES (NULL, "Gentle Repose");
INSERT INTO CLERICSPELLS VALUES (NULL, "Hold Person");
INSERT INTO CLERICSPELLS VALUES (NULL, "Lesser Restoration");
INSERT INTO CLERICSPELLS VALUES (NULL, "Locate Object");
INSERT INTO CLERICSPELLS VALUES (NULL, "Prayer of Healing");
INSERT INTO CLERICSPELLS VALUES (NULL, "Protection from Poison");
INSERT INTO CLERICSPELLS VALUES (NULL, "Silence");
INSERT INTO CLERICSPELLS VALUES (NULL, "Spiritual Weapon");
INSERT INTO CLERICSPELLS VALUES (NULL, "Warding Bond");
INSERT INTO CLERICSPELLS VALUES (NULL, "Zone of Truth");
INSERT INTO CLERICSPELLS VALUES (NULL, "Animate Dead");								-- 3
INSERT INTO CLERICSPELLS VALUES (NULL, "Beacon of Hope");
INSERT INTO CLERICSPELLS VALUES (NULL, "Bestow Curse");
INSERT INTO CLERICSPELLS VALUES (NULL, "Clairvoyance");
INSERT INTO CLERICSPELLS VALUES (NULL, "Create Food and Water");
INSERT INTO CLERICSPELLS VALUES (NULL, "Daylight");
INSERT INTO CLERICSPELLS VALUES (NULL, "Dispel Magic");
INSERT INTO CLERICSPELLS VALUES (NULL, "Feign Death");
INSERT INTO CLERICSPELLS VALUES (NULL, "Glyph of Warding");
INSERT INTO CLERICSPELLS VALUES (NULL, "Magic Circle");
INSERT INTO CLERICSPELLS VALUES (NULL, "Mass Healing Word");
INSERT INTO CLERICSPELLS VALUES (NULL, "Meld into Stone");
INSERT INTO CLERICSPELLS VALUES (NULL, "Protection from Energy");
INSERT INTO CLERICSPELLS VALUES (NULL, "Remove Curse");
INSERT INTO CLERICSPELLS VALUES (NULL, "Revivify");
INSERT INTO CLERICSPELLS VALUES (NULL, "Sending");
INSERT INTO CLERICSPELLS VALUES (NULL, "Speak with Dead");
INSERT INTO CLERICSPELLS VALUES (NULL, "Spirit Guardians");
INSERT INTO CLERICSPELLS VALUES (NULL, "Tongues");
INSERT INTO CLERICSPELLS VALUES (NULL, "Water Walk");
INSERT INTO CLERICSPELLS VALUES (NULL, "Banishment");									-- 4
INSERT INTO CLERICSPELLS VALUES (NULL, "Control Water");
INSERT INTO CLERICSPELLS VALUES (NULL, "Death Ward");
INSERT INTO CLERICSPELLS VALUES (NULL, "Divination");
INSERT INTO CLERICSPELLS VALUES (NULL, "Freedom of Movement");
INSERT INTO CLERICSPELLS VALUES (NULL, "Guardian of Faith");
INSERT INTO CLERICSPELLS VALUES (NULL, "Locate Creature");
INSERT INTO CLERICSPELLS VALUES (NULL, "Stone Shape");
INSERT INTO CLERICSPELLS VALUES (NULL, "Commune");										-- 5
INSERT INTO CLERICSPELLS VALUES (NULL, "Contagion");
INSERT INTO CLERICSPELLS VALUES (NULL, "Dispel Evil and Good");
INSERT INTO CLERICSPELLS VALUES (NULL, "Flame Strike");
INSERT INTO CLERICSPELLS VALUES (NULL, "Geas");
INSERT INTO CLERICSPELLS VALUES (NULL, "Greater Restoration");
INSERT INTO CLERICSPELLS VALUES (NULL, "Hallow");
INSERT INTO CLERICSPELLS VALUES (NULL, "Insect Plague");
INSERT INTO CLERICSPELLS VALUES (NULL, "Legend Lore");
INSERT INTO CLERICSPELLS VALUES (NULL, "Mass Cure Wounds");
INSERT INTO CLERICSPELLS VALUES (NULL, "Planar Binding");
INSERT INTO CLERICSPELLS VALUES (NULL, "Raise Dead");
INSERT INTO CLERICSPELLS VALUES (NULL, "Scrying");
INSERT INTO CLERICSPELLS VALUES (NULL, "Blade Barrier");							-- 6
INSERT INTO CLERICSPELLS VALUES (NULL, "Create Undead");
INSERT INTO CLERICSPELLS VALUES (NULL, "Find the Path");
INSERT INTO CLERICSPELLS VALUES (NULL, "Forbiddance");
INSERT INTO CLERICSPELLS VALUES (NULL, "Harm");
INSERT INTO CLERICSPELLS VALUES (NULL, "Heal");
INSERT INTO CLERICSPELLS VALUES (NULL, "Heroes' Feast");
INSERT INTO CLERICSPELLS VALUES (NULL, "Planar Ally");
INSERT INTO CLERICSPELLS VALUES (NULL, "True Seeing");
INSERT INTO CLERICSPELLS VALUES (NULL, "Word of Recall");
INSERT INTO CLERICSPELLS VALUES (NULL, "Conjure Celestial");					-- 7
INSERT INTO CLERICSPELLS VALUES (NULL, "Divine Word");
INSERT INTO CLERICSPELLS VALUES (NULL, "Etherealness");
INSERT INTO CLERICSPELLS VALUES (NULL, "Fire Storm");
INSERT INTO CLERICSPELLS VALUES (NULL, "Plane Shift");
INSERT INTO CLERICSPELLS VALUES (NULL, "Regenerate");
INSERT INTO CLERICSPELLS VALUES (NULL, "Resurrection");
INSERT INTO CLERICSPELLS VALUES (NULL, "Symbol");
INSERT INTO CLERICSPELLS VALUES (NULL, "Antimagic Field");						-- 8
INSERT INTO CLERICSPELLS VALUES (NULL, "Control Weather");
INSERT INTO CLERICSPELLS VALUES (NULL, "Earthquake");
INSERT INTO CLERICSPELLS VALUES (NULL, "Holy Aura");
INSERT INTO CLERICSPELLS VALUES (NULL, "Astral Projection");					-- 9
INSERT INTO CLERICSPELLS VALUES (NULL, "Gate");
INSERT INTO CLERICSPELLS VALUES (NULL, "Mass Heal");
INSERT INTO CLERICSPELLS VALUES (NULL, "True Resurrection");
-- XGE
INSERT INTO CLERICSPELLS VALUES (NULL, "Toll the Dead");
INSERT INTO CLERICSPELLS VALUES (NULL, "Word of Radiance");
INSERT INTO CLERICSPELLS VALUES (NULL, "Ceremony");
INSERT INTO CLERICSPELLS VALUES (NULL, "Life Transference");
INSERT INTO CLERICSPELLS VALUES (NULL, "Dawn");
INSERT INTO CLERICSPELLS VALUES (NULL, "Holy Weapon");
INSERT INTO CLERICSPELLS VALUES (NULL, "Temple of the Gods");
-- TCE
INSERT INTO CLERICSPELLS VALUES (NULL, "Spirit Shroud");
INSERT INTO CLERICSPELLS VALUES (NULL, "Summon Celestial");

-- DRUIDSPELLS SPELLS
-- PHB
INSERT INTO DRUIDSPELLS VALUES (NULL, "Druidcraft");									-- 0
INSERT INTO DRUIDSPELLS VALUES (NULL, "Guidance");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Mending");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Poison Spray");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Produce Flame");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Resistance");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Shillelagh");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Thorn Whip");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Animal Friendship");						-- 1
INSERT INTO DRUIDSPELLS VALUES (NULL, "Charm Person");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Create or Destroy Water");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Cure Wounds");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Detect Magic");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Detect Poison and Disease");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Entangle");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Faerie Fire");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Fog Cloud");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Goodberry");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Healing Word");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Jump");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Longstrider");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Purify Food and Drink");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Speak with Animals");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Thunderwave");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Animal Messenger");						-- 2
INSERT INTO DRUIDSPELLS VALUES (NULL, "Barkskin");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Beast Sense");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Darkvision");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Enhance Ability");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Find Traps");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Flame Blade");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Flaming Sphere");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Gust of Wind");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Heat Metal");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Hold Person");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Lesser Restoration");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Locate Animals or Plants");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Locate Object");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Moonbeam");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Pass without Trace");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Protection from Poison");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Spike Growth");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Call Lightning");							-- 3
INSERT INTO DRUIDSPELLS VALUES (NULL, "Conjure Animals");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Daylight");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Dispel Magic");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Feign Death");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Meld into Stone");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Plant Growth");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Protection from Energy");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Sleet Storm");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Speak with Plants");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Water Breathing");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Water Walk");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Wind Wall");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Blight");											-- 4
INSERT INTO DRUIDSPELLS VALUES (NULL, "Confusion");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Conjure Minor Elementals");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Conjure Woodland Beings");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Control Water");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Dominate Beast");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Freedom of Movement");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Giant Insect");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Grasping Vine");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Hallucinatory Terrain");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Ice Storm");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Locate Creature");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Polymorph");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Stone Shape");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Stoneskin");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Wall of Fire");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Antilife Shell");							-- 5
INSERT INTO DRUIDSPELLS VALUES (NULL, "Awaken");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Commune with Nature");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Conjure Elemental");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Contagion");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Geas");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Greater Restoration");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Insect Plague");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Mass Cure Wounds");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Planar Binding");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Reincarnate");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Scrying");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Tree Stride");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Wall of Stone");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Conjure Fey");									-- 6
INSERT INTO DRUIDSPELLS VALUES (NULL, "Find the Path");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Heal");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Heroes' Feast");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Move Earth");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Sunbeam");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Transport via Plants");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Wall of Thorns");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Wind Walk");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Fire Storm");									-- 7
INSERT INTO DRUIDSPELLS VALUES (NULL, "Mirage Arcane");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Plane Shift");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Regenerate");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Reverse Gravity");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Animal Shapes");								-- 8
INSERT INTO DRUIDSPELLS VALUES (NULL, "Antipathy/Sympathy");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Control Weather");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Earthquake");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Feeblemind");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Sunburst");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Tsunami");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Foresight");										-- 9
INSERT INTO DRUIDSPELLS VALUES (NULL, "Shapechange");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Storm of Vengeance");
INSERT INTO DRUIDSPELLS VALUES (NULL, "True Resurrection");
-- XGE
INSERT INTO DRUIDSPELLS VALUES (NULL, "Control Flames");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Create Bonfire");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Frostbite");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Gust");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Infestation");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Magic Stone");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Mold Earth");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Primal Savagery");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Shape Water");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Thunderclap");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Absorb Elements");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Beast Bond");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Earth Tremor");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Ice Knife");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Snare");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Dust Devil");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Earthbind");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Healing Spirit");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Skywrite");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Warding Wind");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Erupting Earth");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Flame Arrows");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Tidal Wave");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Wall of Water");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Charm Monster");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Elemental Bane");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Guardian of Nature");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Watery Sphere");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Control Winds");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Maelstrom");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Transmute Rock");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Wrath of Nature");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Bones of the Earth");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Druid Grove");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Investiture of Flame");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Investiture of Ice");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Investiture of Stone");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Investiture of Wind");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Primordial Ward");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Whirlwind");
-- TCE
INSERT INTO DRUIDSPELLS VALUES (NULL, "Summon Beast");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Summon Fey");
INSERT INTO DRUIDSPELLS VALUES (NULL, "Summon Elemental");

-- PALADINSPELLS SPELLS
-- PHB
INSERT INTO PALADINSPELLS VALUES (NULL, "Bless");														-- 1
INSERT INTO PALADINSPELLS VALUES (NULL, "Command");
INSERT INTO PALADINSPELLS VALUES (NULL, "Compelled Duel");
INSERT INTO PALADINSPELLS VALUES (NULL, "Cure Wounds");
INSERT INTO PALADINSPELLS VALUES (NULL, "Detect Evil and Good");
INSERT INTO PALADINSPELLS VALUES (NULL, "Detect Magic");
INSERT INTO PALADINSPELLS VALUES (NULL, "Detect Poison and Disease");
INSERT INTO PALADINSPELLS VALUES (NULL, "Divine Favor");
INSERT INTO PALADINSPELLS VALUES (NULL, "Heroism");
INSERT INTO PALADINSPELLS VALUES (NULL, "Protection from Evil and Good");
INSERT INTO PALADINSPELLS VALUES (NULL, "Purify Food and Drink");
INSERT INTO PALADINSPELLS VALUES (NULL, "Searing Smite");
INSERT INTO PALADINSPELLS VALUES (NULL, "Shield of Faith");
INSERT INTO PALADINSPELLS VALUES (NULL, "Thunderous Smite");
INSERT INTO PALADINSPELLS VALUES (NULL, "Wrathful Smite");
INSERT INTO PALADINSPELLS VALUES (NULL, "Aid");															-- 2
INSERT INTO PALADINSPELLS VALUES (NULL, "Branding Smite");
INSERT INTO PALADINSPELLS VALUES (NULL, "Find Steed");
INSERT INTO PALADINSPELLS VALUES (NULL, "Lesser Restoration");
INSERT INTO PALADINSPELLS VALUES (NULL, "Locate Object");
INSERT INTO PALADINSPELLS VALUES (NULL, "Magic Weapon");
INSERT INTO PALADINSPELLS VALUES (NULL, "Protection from Poison");
INSERT INTO PALADINSPELLS VALUES (NULL, "Zone of Truth");
INSERT INTO PALADINSPELLS VALUES (NULL, "Aura of Vitality");								-- 3
INSERT INTO PALADINSPELLS VALUES (NULL, "Blinding Smite");
INSERT INTO PALADINSPELLS VALUES (NULL, "Create Food and Water");
INSERT INTO PALADINSPELLS VALUES (NULL, "Crusader's Mantle");
INSERT INTO PALADINSPELLS VALUES (NULL, "Daylight");
INSERT INTO PALADINSPELLS VALUES (NULL, "Dispel Magic");
INSERT INTO PALADINSPELLS VALUES (NULL, "Elemental Weapon");
INSERT INTO PALADINSPELLS VALUES (NULL, "Magic Circle");
INSERT INTO PALADINSPELLS VALUES (NULL, "Remove Curse");
INSERT INTO PALADINSPELLS VALUES (NULL, "Revivify");
INSERT INTO PALADINSPELLS VALUES (NULL, "Aura of Life");										-- 4
INSERT INTO PALADINSPELLS VALUES (NULL, "Aura of Purity");
INSERT INTO PALADINSPELLS VALUES (NULL, "Banishment");
INSERT INTO PALADINSPELLS VALUES (NULL, "Death Ward");
INSERT INTO PALADINSPELLS VALUES (NULL, "Locate Creature");
INSERT INTO PALADINSPELLS VALUES (NULL, "Staggering Smite");
INSERT INTO PALADINSPELLS VALUES (NULL, "Banishing Smite");									-- 5
INSERT INTO PALADINSPELLS VALUES (NULL, "Circle of Power");
INSERT INTO PALADINSPELLS VALUES (NULL, "Destructive Wave");
INSERT INTO PALADINSPELLS VALUES (NULL, "Dispel Evil and Good");
INSERT INTO PALADINSPELLS VALUES (NULL, "Geas");
INSERT INTO PALADINSPELLS VALUES (NULL, "Raise Dead");
-- XGE
INSERT INTO PALADINSPELLS VALUES (NULL, "Ceremony");
INSERT INTO PALADINSPELLS VALUES (NULL, "Find Greater Steed");
INSERT INTO PALADINSPELLS VALUES (NULL, "Holy Weapon");
-- TCE
INSERT INTO PALADINSPELLS VALUES (NULL, "Spirit Shroud");
INSERT INTO PALADINSPELLS VALUES (NULL, "Summon Celestial");

-- RANGERSPELLS SPELLS
-- PHB
INSERT INTO RANGERSPELLS VALUES (NULL, "Alarm");														-- 1
INSERT INTO RANGERSPELLS VALUES (NULL, "Animal Friendship");
INSERT INTO RANGERSPELLS VALUES (NULL, "Cure Wounds");
INSERT INTO RANGERSPELLS VALUES (NULL, "Detect Magic");
INSERT INTO RANGERSPELLS VALUES (NULL, "Detect Poison and Disease");
INSERT INTO RANGERSPELLS VALUES (NULL, "Ensnaring Strike");
INSERT INTO RANGERSPELLS VALUES (NULL, "Fog Cloud");
INSERT INTO RANGERSPELLS VALUES (NULL, "Goodberry");
INSERT INTO RANGERSPELLS VALUES (NULL, "Hail of Thorns");
INSERT INTO RANGERSPELLS VALUES (NULL, "Hunter's Mark");
INSERT INTO RANGERSPELLS VALUES (NULL, "Jump");
INSERT INTO RANGERSPELLS VALUES (NULL, "Longstrider");
INSERT INTO RANGERSPELLS VALUES (NULL, "Speak with Animals");
INSERT INTO RANGERSPELLS VALUES (NULL, "Animal Messenger");									-- 2
INSERT INTO RANGERSPELLS VALUES (NULL, "Barkskin");
INSERT INTO RANGERSPELLS VALUES (NULL, "Beast Sense");
INSERT INTO RANGERSPELLS VALUES (NULL, "Cordon of Arrows");
INSERT INTO RANGERSPELLS VALUES (NULL, "Darkvision");
INSERT INTO RANGERSPELLS VALUES (NULL, "Find Traps");
INSERT INTO RANGERSPELLS VALUES (NULL, "Lesser Restoration");
INSERT INTO RANGERSPELLS VALUES (NULL, "Locate Animals or Plants");
INSERT INTO RANGERSPELLS VALUES (NULL, "Locate Object");
INSERT INTO RANGERSPELLS VALUES (NULL, "Pass without Trace");
INSERT INTO RANGERSPELLS VALUES (NULL, "Protection from Poison");
INSERT INTO RANGERSPELLS VALUES (NULL, "Silence");
INSERT INTO RANGERSPELLS VALUES (NULL, "Spike Growth");
INSERT INTO RANGERSPELLS VALUES (NULL, "Conjure Animals");									-- 3
INSERT INTO RANGERSPELLS VALUES (NULL, "Conjure Barrage");
INSERT INTO RANGERSPELLS VALUES (NULL, "Daylight");
INSERT INTO RANGERSPELLS VALUES (NULL, "Lightning Arrow");
INSERT INTO RANGERSPELLS VALUES (NULL, "Nondetection");
INSERT INTO RANGERSPELLS VALUES (NULL, "Plant Growth");
INSERT INTO RANGERSPELLS VALUES (NULL, "Protection from Energy");
INSERT INTO RANGERSPELLS VALUES (NULL, "Speak with Plants");
INSERT INTO RANGERSPELLS VALUES (NULL, "Water Breathing");
INSERT INTO RANGERSPELLS VALUES (NULL, "Water Walk");
INSERT INTO RANGERSPELLS VALUES (NULL, "Wind Wall");
INSERT INTO RANGERSPELLS VALUES (NULL, "Conjure Woodland Beings");					-- 4
INSERT INTO RANGERSPELLS VALUES (NULL, "Freedom of Movement");
INSERT INTO RANGERSPELLS VALUES (NULL, "Grasping Vine");
INSERT INTO RANGERSPELLS VALUES (NULL, "Locate Creature");
INSERT INTO RANGERSPELLS VALUES (NULL, "Stoneskin");
INSERT INTO RANGERSPELLS VALUES (NULL, "Commune with Nature");							-- 5
INSERT INTO RANGERSPELLS VALUES (NULL, "Conjure Volley");
INSERT INTO RANGERSPELLS VALUES (NULL, "Swift Quiver");
INSERT INTO RANGERSPELLS VALUES (NULL, "Tree Stride");
-- XGE
INSERT INTO RANGERSPELLS VALUES (NULL, "Absorb Elements");
INSERT INTO RANGERSPELLS VALUES (NULL, "Beast Bond");
INSERT INTO RANGERSPELLS VALUES (NULL, "Snare");
INSERT INTO RANGERSPELLS VALUES (NULL, "Zephyr Strike");
INSERT INTO RANGERSPELLS VALUES (NULL, "Healing Spirit");
INSERT INTO RANGERSPELLS VALUES (NULL, "Flame Arrows");
INSERT INTO RANGERSPELLS VALUES (NULL, "Guardian of Nature");
INSERT INTO RANGERSPELLS VALUES (NULL, "Steel Wind Strike");
INSERT INTO RANGERSPELLS VALUES (NULL, "Wrath of Nature");
-- TCE
INSERT INTO RANGERSPELLS VALUES (NULL, "Summon Beast");
INSERT INTO RANGERSPELLS VALUES (NULL, "Summon Fey");
INSERT INTO RANGERSPELLS VALUES (NULL, "Summon Elemental");

-- SORCERERSPELLS SPELLS
-- PHB
INSERT INTO SORCERERSPELLS VALUES (NULL, "Acid Splash");										-- 0
INSERT INTO SORCERERSPELLS VALUES (NULL, "Blade Ward");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Chill Touch");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Dancing Lights");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Fire Bolt");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Friends");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Light");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Mage Hand");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Mending");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Message");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Minor Illusion");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Poison Spray");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Prestidigitation");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Ray of Frost");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Shocking Grasp");
INSERT INTO SORCERERSPELLS VALUES (NULL, "True Strike");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Burning Hands");									-- 1
INSERT INTO SORCERERSPELLS VALUES (NULL, "Charm Person");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Chromatic Orb");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Color Spray");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Comprehend Languages");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Detect Magic");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Disguise Self");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Expeditious Retreat");
INSERT INTO SORCERERSPELLS VALUES (NULL, "False Life");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Feather Fall");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Fog Cloud");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Jump");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Mage Armor");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Magic Missile");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Ray of Sickness");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Shield");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Silent Image");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Sleep");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Thunderwave");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Witch Bolt");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Alter Self");											-- 2
INSERT INTO SORCERERSPELLS VALUES (NULL, "Blindness/Deafness");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Blur");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Cloud of Daggers");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Crown of Madness");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Darkness");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Darkvision");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Detect Thoughts");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Enhance Ability");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Enlarge/Reduce");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Gust of Wind");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Hold Person");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Invisibility");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Knock");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Levitate");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Mirror Image");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Misty Step");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Phantasmal Force");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Scorching Ray");
INSERT INTO SORCERERSPELLS VALUES (NULL, "See Invisibility");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Shatter");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Spider Climb");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Suggestion");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Web");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Blink");													-- 3
INSERT INTO SORCERERSPELLS VALUES (NULL, "Clairvoyance");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Counterspell");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Daylight");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Dispel Magic");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Fear");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Fireball");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Fly");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Gaseous Form");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Haste");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Hypnotic Pattern");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Lightning Bolt");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Major Image");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Protection from Energy");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Sleet Storm");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Slow");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Stinking Cloud");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Tongues");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Water Breathing");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Water Walk");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Banishment");											-- 4
INSERT INTO SORCERERSPELLS VALUES (NULL, "Blight");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Confusion");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Dimension Door");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Dominate Beast");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Greater Invisibility");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Ice Storm");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Polymorph");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Stoneskin");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Wall of Fire");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Animate Objects");								-- 5
INSERT INTO SORCERERSPELLS VALUES (NULL, "Cloudkill");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Cone of Cold");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Creation");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Dominate Person");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Hold Monster");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Insect Plague");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Seeming");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Telekinesis");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Teleportation Circle");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Wall of Stone");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Arcane Gate");										-- 6
INSERT INTO SORCERERSPELLS VALUES (NULL, "Chain Lightning");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Circle of Death");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Disintegrate");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Eyebite");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Globe of Invulnerability");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Mass Suggestion");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Move Earth");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Sunbeam");
INSERT INTO SORCERERSPELLS VALUES (NULL, "True Seeing");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Delayed Blast Fireball");					-- 7
INSERT INTO SORCERERSPELLS VALUES (NULL, "Etherealness");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Finger of Death");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Fire Storm");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Plane Shift");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Prismatic Spray");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Reverse Gravity");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Teleport");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Dominate Monster");								-- 8
INSERT INTO SORCERERSPELLS VALUES (NULL, "Earthquake");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Incendiary Cloud");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Power Word Stun");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Sunburst");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Gate");														-- 9
INSERT INTO SORCERERSPELLS VALUES (NULL, "Meteor Swarm");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Power Word Kill");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Time Stop");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Wish");
-- XGE
INSERT INTO SORCERERSPELLS VALUES (NULL, "Control Flames");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Create Bonfire");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Frostbite");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Gust");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Infestation");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Mold Earth");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Shape Water");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Thunderclap");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Absorb Elements");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Catapult");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Chaos Bolt");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Earth Tremor");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Ice Knife");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Aganazzar's Scorcher");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Dragon's Breath");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Dust Devil");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Earthbind");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Maximilian's Earthen Grasp");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Mind Spike");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Pyrotechnics");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Shadow Blade");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Snilloc's Snowball Swarm");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Warding Wind");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Catnap");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Enemies Abound");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Erupting Earth");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Flame Arrows");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Melf's Minute Meteors");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Thunder Step");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Tidal Wave");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Wall of Water");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Charm Monster");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Sickening Radiance");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Storm Sphere");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Vitriolic Sphere");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Watery Sphere");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Control Winds");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Enervation");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Far Step");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Immolation");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Skill Empowerment");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Synaptic Static");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Wall of Light");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Investiture of Flame");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Investiture of Ice");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Investiture of Stone");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Investiture of Wind");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Mental Prison");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Scatter");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Crown of Stars");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Power Word Pain");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Whirlwind");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Abi-Dalzim's Horrid Wilting");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Mass Polymorph");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Psychic Scream");
-- TCE
INSERT INTO SORCERERSPELLS VALUES (NULL, "Booming Blade");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Green-Flame Blade");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Lightning Lure");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Mind Sliver");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Sword Burst");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Tasha's Caustic Brew");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Tasha's Mind Whip");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Intellect Fortress");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Tasha's Otherworldly Guise");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Dream of the Blue Veil");
INSERT INTO SORCERERSPELLS VALUES (NULL, "Blade of Disaster");

-- WARLOCKSPELLS SPELLS
-- PHB
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Blade Ward");											-- 0
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Chill Touch");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Eldritch Blast");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Friends");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Mage Hand");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Minor Illusion");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Poison Spray");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Prestidigitation");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "True Strike");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Armor of Agathys");								-- 1
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Arms of Hadar");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Charm Person");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Comprehend Languages");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Expeditious Retreat");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Hellish Rebuke");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Hex");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Illusory Script");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Protection from Evil and Good");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Unseen Servant");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Witch Bolt");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Cloud of Daggers");								-- 2
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Crown of Madness");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Darkness");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Enthrall");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Hold Person");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Invisibility");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Mirror Image");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Misty Step");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Ray of Enfeeblement");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Shatter");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Spider Climb");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Suggestion");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Counterspell");										-- 3
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Dispel Magic");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Fear");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Fly");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Gaseous Form");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Hunger of Hadar");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Hypnotic Pattern");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Magic Circle");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Major Image");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Remove Curse");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Tongues");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Vampiric Touch");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Banishment");											-- 4
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Blight");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Dimension Door");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Hallucinatory Terrain");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Contact Other Plane");							-- 5
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Dream");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Hold Monster");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Scrying");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Arcane Gate");											-- 6
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Circle of Death");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Conjure Fey");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Create Undead");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Eyebite");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Flesh to Stone");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Mass Suggestion");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "True Seeing");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Etherealness");										-- 7
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Finger of Death");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Forcecage");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Plane Shift");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Demiplane");												-- 8
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Dominate Monster");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Feeblemind");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Glibness");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Power Word Stun");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Astral Projection");								-- 9
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Foresight");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Imprisonment");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Power Word Kill");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "True Polymorph");
-- Additional spells based on invocations
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Dissonant Whispers");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Tasha's Hideous Laughter");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Detect Thoughts");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Phantasmal Force");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Clairvoyance");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Sending");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Dominate Beast");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Evard's Black Tentacles");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Dominate Person");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Telekinesis");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Alter Self");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Arcane Eye");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Bane");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Bestow Curse");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Compulsion");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Confusion");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Conjure Elemental");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Detect Magic");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Disguise Self");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "False Life");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Hold Monster");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Jump");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Levitate");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Mage Armour");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Polymorph");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Silent Image");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Slow");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Speak with Animals");
-- INSERT INTO WARLOCKSPELLS VALUES (NULL, "Speak with Dead");
-- XGE
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Create Bonfire");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Frostbite");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Infestation");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Magic Stone");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Thunderclap");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Toll the Dead");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Cause Fear");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Earthbind");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Mind Spike");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Shadow Blade");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Enemies Abound");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Thunder Step");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Summon Lesser Demons");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Charm Monster");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Elemental Bane");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Shadow of Moil");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Sickening Radiance");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Summon Greater Demon");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Danse Macabre");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Enervation");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Far Step");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Infernal Calling");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Negative Energy Flood");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Synaptic Static");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Wall of Light");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Investiture of Flame");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Investiture of Ice");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Investiture of Stone");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Investiture of Wind");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Mental Prison");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Scatter");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Soul Cage");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Crown of Stars");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Power Word Pain");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Maddening Darkness");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Psychic Scream");
-- TCE
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Booming Blade");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Green-Flame Blade");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Lightning Lure");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Mind Sliver");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Sword Burst");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Intellect Fortress");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Spirit Shroud");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Summon Fey");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Summon Shadowspawn");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Summon Undead");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Summon Aberration");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Summon Fiend");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Tasha's Otherworldly Guise");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Dream of the Blue Veil");
INSERT INTO WARLOCKSPELLS VALUES (NULL, "Blade of Disaster");

-- WIZARDSPELLS SPELLS
-- PHB
INSERT INTO WIZARDSPELLS VALUES (NULL, "Acid Splash");												-- 0
INSERT INTO WIZARDSPELLS VALUES (NULL, "Blade Ward");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Chill Touch");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Dancing Lights");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Fire Bolt");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Friends");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Light");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mage Hand");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mending");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Message");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Minor Illusion");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Poison Spray");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Prestidigitation");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Ray of Frost");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Shocking Grasp");
INSERT INTO WIZARDSPELLS VALUES (NULL, "True Strike");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Alarm");															-- 1
INSERT INTO WIZARDSPELLS VALUES (NULL, "Burning Hands");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Charm Person");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Chromatic Orb");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Color Spray");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Comprehend Languages");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Detect Magic");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Disguise Self");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Expeditious Retreat");
INSERT INTO WIZARDSPELLS VALUES (NULL, "False Life");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Feather Fall");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Find Familiar");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Fog Cloud");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Grease");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Identify");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Illusory Script");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Jump");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Longstrider");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mage Armor");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Magic Missile");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Protection from Evil and Good");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Ray of Sickness");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Shield");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Silent Image");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Sleep");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Tasha's Hideous Laughter");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Tenser's Floating Disk");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Thunderwave");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Unseen Servant");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Witch Bolt");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Alter Self");													-- 2
INSERT INTO WIZARDSPELLS VALUES (NULL, "Arcane Lock");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Blindness/Deafness");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Blur");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Cloud of Daggers");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Continual Flame");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Crown of Madness");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Darkness");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Darkvision");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Detect Thoughts");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Enlarge/Reduce");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Flaming Sphere");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Gentle Repose");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Gust of Wind");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Hold Person");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Invisibility");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Knock");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Levitate");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Locate Object");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Magic Mouth");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Magic Weapon");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Melf's Acid Arrow");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mirror Image");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Misty Step");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Nystul's Magic Aura");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Phantasmal Force");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Ray of Enfeeblement");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Rope Trick");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Scorching Ray");
INSERT INTO WIZARDSPELLS VALUES (NULL, "See Invisibility");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Shatter");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Spider Climb");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Suggestion");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Web");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Animate Dead");												-- 3
INSERT INTO WIZARDSPELLS VALUES (NULL, "Bestow Curse");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Blink");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Clairvoyance");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Counterspell");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Dispel Magic");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Fear");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Feign Death");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Fireball");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Fly");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Gaseous Form");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Glyph of Warding");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Haste");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Hypnotic Pattern");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Leomund's Tiny Hut");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Lightning Bolt");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Magic Circle");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Major Image");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Nondetection");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Phantom Steed");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Protection from Energy");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Remove Curse");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Sending");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Sleet Storm");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Slow");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Stinking Cloud");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Tongues");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Vampiric Touch");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Water Breathing");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Arcane Eye");													-- 4
INSERT INTO WIZARDSPELLS VALUES (NULL, "Banishment");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Blight");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Confusion");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Conjure Minor Elementals");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Control Water");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Dimension Door");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Evard's Black Tentacles");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Fabricate");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Fire Shield");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Greater Invisibility");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Hallucinatory Terrain");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Ice Storm");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Leomund's Secret Chest");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Locate Creature");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mordenkainen's Faithful Hound");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mordenkainen's Private Sanctum");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Otiluke's Resilient Sphere");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Phantasmal Killer");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Polymorph");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Stone Shape");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Stoneskin");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Wall of Fire");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Animate Objects");										-- 5
INSERT INTO WIZARDSPELLS VALUES (NULL, "Bigby's Hand");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Cloudkill");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Cone of Cold");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Conjure Elemental");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Contact Other Plane");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Creation");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Dominate Person");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Dream");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Geas");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Hold Monster");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Legend Lore");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mislead");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Modify Memory");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Passwall");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Planar Binding");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Rary's Telepathic Bond");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Scrying");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Seeming");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Telekinesis");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Teleportation Circle");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Wall of Force");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Wall of Stone");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Arcane Gate");												-- 6
INSERT INTO WIZARDSPELLS VALUES (NULL, "Chain Lightning");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Circle of Death");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Contingency");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Create Undead");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Disintegrate");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Drawmij's Instant Summons");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Eyebite");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Flesh to Stone");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Globe of Invulnerability");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Guards and Wards");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Magic Jar");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mass Suggestion");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Move Earth");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Otiluke's Freezing Sphere");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Otto's Irresistible Dance");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Programmed Illusion");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Sunbeam");
INSERT INTO WIZARDSPELLS VALUES (NULL, "True Seeing");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Wall of Ice");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Delayed Blast Fireball");							-- 7
INSERT INTO WIZARDSPELLS VALUES (NULL, "Etherealness");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Finger of Death");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Forcecage");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mirage Arcane");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mordenkainen's Magnificent Mansion");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mordenkainen's Sword");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Plane Shift");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Prismatic Spray");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Project Image");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Reverse Gravity");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Sequester");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Simulacrum");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Symbol");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Teleport");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Antimagic Field");										-- 8
INSERT INTO WIZARDSPELLS VALUES (NULL, "Antipathy/Sympathy");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Clone");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Control Weather");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Demiplane");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Dominate Monster");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Feeblemind");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Incendiary Cloud");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Maze");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mind Blank");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Power Word Stun");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Sunburst");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Telepathy");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Astral Projection");									-- 9
INSERT INTO WIZARDSPELLS VALUES (NULL, "Foresight");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Gate");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Imprisonment");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Meteor Swarm");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Power Word Kill");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Prismatic Wall");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Shapechange");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Time Stop");
INSERT INTO WIZARDSPELLS VALUES (NULL, "True Polymorph");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Weird");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Wish");
-- XGE
INSERT INTO WIZARDSPELLS VALUES (NULL, "Control flames");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Create bonfire");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Frostbite");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Gust");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Infestation");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mold earth");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Shape water");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Thunderclap");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Toll the Dead");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Absorb elements");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Catapult");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Cause Fear");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Earth tremor");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Ice knife");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Snare");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Aganazzar's scorcher");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Dragon's Breath");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Dust devil");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Earthbind");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Maximilian's earthen grasp");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mind Spike");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Pyrotechnics");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Shadow Blade");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Skywrite");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Snilloc's snowball swarm");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Warding Wind");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Catnap");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Enemies Abound");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Erupting earth");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Flame arrows");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Life Transference");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Melf's minute meteors");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Summon Lesser Demons");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Thunder Step");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Tidal wave");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Tiny Servant");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Wall of sand");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Wall of water");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Charm Monster");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Elemental bane");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Sickening radiance");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Storm sphere");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Summon greater demon");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Vitriolic sphere");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Watery sphere");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Control winds");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Danse Macabre");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Dawn");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Enervation");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Far Step");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Immolation");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Infernal Calling");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Negative energy flood");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Skill empowerment");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Steel wind strike");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Synaptic static");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Transmute rock");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Wall of light");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Create homunculus");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Investiture of flame");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Investiture of ice");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Investiture of stone");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Investiture of wind");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mental prison");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Scatter");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Soul cage");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Tenser's transformation");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Crown of stars");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Power word pain");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Whirlwind");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Abi-Dalzim's horrid wilting");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Illusory dragon");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Maddening darkness");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mighty fortress");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Invulnerability");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mass polymorph");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Psychic scream");
-- TCE
INSERT INTO WIZARDSPELLS VALUES (NULL, "Booming Blade");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Green-Flame Blade");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Lightning Lure");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Mind Sliver");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Sword Burst");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Tasha's Caustic Brew");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Tasha's Mind Whip");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Intellect Fortress");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Spirit Shroud");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Summon Fey");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Summon Shadowspawn");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Summon Undead");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Summon Aberration");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Summon Construct");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Summon Elemental");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Summon Fiend");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Tasha's Otherworldly Guise");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Dream of the Blue Veil");
INSERT INTO WIZARDSPELLS VALUES (NULL, "Blade of Disaster");
