DROP TABLE Users;
CREATE TABLE Users(
	ID INTEGER PRIMARY KEY NOT NULL,
  EMAIL TEXT NOT NULL,
  PASSWORD TEXT NOT NULL,
  USERNAME TEXT NOT NULL,
  ADMIN INTEGER NOT NULL,
  CREATED TEXT NOT NULL,
  ACTIVITY TEXT,
  CHARACTERS TEXT,
  FAV_SPELLS TEXT,
  FAV_ITEMS TEXT,
  FAV_FEATURES TEXT,
  FAV_SUBFEAT TEXT
);